### ISSUE TITLE
Does not work as expected

### ISSUE THREAD

**Issue by bcorcoran** [yazeedobaid/laravel-mix-postcss-config#6]
This package does not work as expected. If I load plugins via the method outlined on https://laravel-mix.com/docs/5.0/css-preprocessors the plugins load as expected and there are no errors.

However, if I use this package with postcss.config.js, the plugins load at a strange point in the build and cause a lot of garbage to be thrown into the console. The errors mostly refer to postcss not having any plugins loaded (so it does nothing) and occur on third-party packages.

Not sure if this is fixable as it's currently built but thought you should know.

**Comment by stanislavhannes** [comment]
Have the same issue wir laravel mix 5 ... If I use the postcss.config.js way, it compiles the files and works as it should (without garbage thrown into the console)

**Comment by yazeedobaid** [comment]
Can you provide any screenshots or a demo project?

**Comment by stanislavhannes** [comment]
sorry, I can't. Already used a different way without this package

**Comment by yazeedobaid** [comment]
I'll have to close this issue since no information is provided.
